[build]
  command = "npm install --legacy-peer-deps --registry=https://registry.npmjs.org/ && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
